### ISSUE TITLE
快速填写城市任务加成数据错误

### ISSUE THREAD

**Issue by lsflling** [lintx/jgm-calculator#10]
服务业示范区
商贸中心 150%
服装店 150%
便利店 150%

正确为
商贸中心 150%
服装店 150%
便利店 100%

![Snipaste_2019-10-18_02-16-50](https://user-images.githubusercontent.com/37450614/67036064-805f0f00-f14d-11e9-93c4-a6ee4af80cce.png)

**Comment by lintx** [comment]
我康康啊

**Comment by lintx** [comment]
看了一下是源数据错误，已经修复了
