### ISSUE TITLE
似乎更新后（v0.11）计算结果不准

### ISSUE THREAD

**Issue by MYSTICA1994** [lintx/jgm-calculator#4]

**Comment by MYSTICA1994** [comment]
问题或许出在政策选择上，上一版的计算正确

**Comment by lintx** [comment]
具体怎么不准呢？你配置是怎么样？跟游戏里面一致吗

**Comment by gityfx2018** [comment]
就是 我说的情况  默认每个阶段的四种为1级了  事实是0级

**Comment by MYSTICA1994** [comment]
> 具体怎么不准呢？你配置是怎么样？跟游戏里面一致吗

先非常感谢你的计算器，帮到了很多！

配置等级一样，家国之光、游记、 城市任务没有变化，政策那块重选后数值偏小，比如我现在同样的配置，游戏中显示127B，这里计算出100B

**Comment by MYSTICA1994** [comment]
> 就是 我说的情况 默认每个阶段的四种为1级了 事实是0级

我是计算器数值小于游戏中数值，你也是吗？

**Comment by gityfx2018** [comment]
嗯是的  我的算出来计算器4.44cc  我实际4.33cc

**Comment by lintx** [comment]
我也出现了，在紧急复查中

**Comment by gityfx2018** [comment]
因为我只完成了第四阶段的城镇化和乡村振兴 各1级 但实际是按照第四阶段 四个都是1级来算的，多了离线80%和全部建筑80%  实际结果也是算出来多了一点点

**Comment by MYSTICA1994** [comment]
离线数据误差小于0.2了，在线数据计算器大于游戏数字

**Comment by lintx** [comment]
政策修复了

**Comment by MYSTICA1994** [comment]
正常啦！谢谢！
