### ISSUE TITLE
关于提升人机交互体验

### ISSUE THREAD

**Issue by kessil** [lintx/jgm-calculator#6]
很赞的后台算法和UI，感谢！在使用过程中发现游记加成要自己算好填上去有点麻烦，建议采取和政策一样的方案，预先收集各地明信片和加成数据提供使用者勾选。相应的**城市任务**的加成数据应该也是可以收集的。这是我收集的明信片供参考，在本地我使用数据透视表进行汇总。

![jgm1](https://user-images.githubusercontent.com/11907802/66450180-26de4c80-ea8a-11e9-87fb-53a335e8ca2b.png)
![jgm2](https://user-images.githubusercontent.com/11907802/66450181-2776e300-ea8a-11e9-98c2-3cff847f3bb9.png)
[游记加成.txt](https://github.com/lintx/jgm-calculator/files/3705505/default.txt)

**Comment by lintx** [comment]
相册太多了，而且游戏内置了总和数据，直接照着填就好了，这个功能没必要

**Comment by lintx** [comment]
并且，我个人不觉得一个个选已完成区域-已完成相册，会比直接照着游戏内总和数据填7个数据更简单，反而会复杂/麻烦很多倍

**Comment by kessil** [comment]
请问总和数据在哪里看？我好像没有找到。。。

**Comment by lintx** [comment]
家国之光-中国游记卡片右上角的星星，在计算器的提示里面也有写的

**Comment by kessil** [comment]
找到了，好愚蠢。我现在将关闭这个issue，作者你可以删除它或者设为无效。感谢您的解答。
