### ISSUE TITLE
希望支持中国游记快速填写

### ISSUE THREAD

**Issue by icylight** [lintx/jgm-calculator#9]
希望能有这两个功能
-  部分游记：用数组存每个区的加成，快速填写填写出生地和当前相册，然后通过出生地把初始相册位置找到。根据游记的顺序把每个地区的加成加在一起作为游记的加成。
- 还希望支持一个一键加成全部游记

[\[攻略\](相册开启顺序)各地区相册轮换开启顺序 以及 开启多个相册后增益之和](https://bbs.nga.cn/read.php?tid=18748152&_fp=5)
[[攻略] 各地区相册加成
](https://bbs.nga.cn/read.php?tid=18688989)

**Comment by lintx** [comment]
Duplicate of #6

**Comment by icylight** [comment]
我和 #6 的想法不太一样：
#6 是手动选每一个游记；
我的意思是选游记开始和当前游记。现在游记的顺序是一致的，**在相册开全的情况下**，只要知道开始游记和结束游记，就可以计算出所对应的结果了。

输入参数就两个，一个是开始的游记，另一个是结束的游记
比如我现在的状态，开始：`江水人家`，结束：`平原古风`，然后由代码根据 [顺序](https://bbs.nga.cn/read.php?tid=18748152&_fp=5) 计算从 `江水人家` 到 `平原古风` 的加成，然后填入计算参数里面。
游记开始可以根据所在地判断，`江水人家` 对应了 `重庆、湖北、湖南、江西` 四个省。所以开始的地方可以通过填写所在地查找出来。
游记结束可以在开包页面找到。

当然，正常使用更改游记配置频率的很低。不优化游记的填写也对使用影响不大。
